baseURL = "https://annemarievdmarel.github.io/"
languageCode = "en"
title = "Annemarie van der Marel"
theme = "hugo-initio"

[params]
    name = "Annemarie van der Marel"
    description = "Behavioral ecologist studying social evolution"
    email = "avdmarel@outlook.com"
    phone = ""
    position = "FONDECYT postdoctoral follow 2022"
    affiliation = "Pontificia Universidad Católica de Chile"
    year = 2023
    avatar = "am-academic-website/images/me 2023-cropped.jpg"
    avatarclass = "circle"
    background = ""
    banner = "am-academic-website/images/rainbow Tindaya.jpg"
    favicon = ""
    DateForm = "August 2023"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = false
    showServices = false
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fab fa-facebook-square"
    footer = false
    sharethis = false
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/avdmarel"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fab fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google scholar"
	url = "https://scholar.google.nl/citations?user=EqBkyH8AAAAJ&hl=en"
    icon = "fab fa-google-scholar"
    footer = true
    sharethis = true
    network = "googlescholar"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/annemarie-van-der-marel-9a63b688/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/annemarievdmarel"
    icon = "fab fa-github"
    footer = true
    sharethis = true
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:avdmarel@outlook.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
